name: Android CI

on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'develop/*'
  pull_request:
    branches:
      - main
      - 'feature/*'
      - 'develop/*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: ['8.0.382+5', '11.0.24+8', '17'] 

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: gradle

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-jdk-${{ matrix.java-version }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-jdk-${{ matrix.java-version }}-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: app/build/outputs/**/*.apk
